name: "Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The tag to target"
        required: false
jobs:
  full-release:
    runs-on: ubuntu-latest
    # permissions:
    #   # This is useful if you want to use PyPI trusted publisher
    #   # and NPM provenance
    #   id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          ref: ref/tags/${{ inputs.version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v2

      - run: yarn

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Publish labextension NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          skip_existing: true
