name: "Release"
on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U wheel twine setuptools packaging jupyterlab-pygments==0.2.2 jupyterlab==3.6.6

    - name: Lint the extension
      run: |
        set -eux
        jlpm
        jlpm run lint:check
    
    - name: Build the extension
      run: |
        set -eux

        python -m pip install .[test]

        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie ".*jupyterlab-disable-download.*ok"
        python -m jupyterlab.browser_check

    - name: Package the extension
      run: |
        set -eux

        pip install build
        python -m build
        pip uninstall -y "jupyterlab-disable-download" jupyterlab
  
    - name: upload python build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
        retention-days: 5

    - name: upload typescript build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: lib
        retention-days: 5

  publish-python:
    name: Publish python package
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Display structure of downloaded dist
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Uzip dist folder
        run: zip -r dist.zip dist/

      - name: List artifacts 
        run: ls -R

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true


  publish-npm:
    name: Publish npm package
    needs: publish-python
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          ref: ref/tags/${{ inputs.version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Uzip dist folder
        run: zip -r dist.zip dist/

      - name: List artifacts 
        run: ls -R

      - run: yarn

      - name: Publish labextension NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          strategy: "upgrade"
          skip_existing: true
